title: clubby789's Blog
email: clubby789@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'll be using this blog to post Hackthebox writeups, among other projects that I'm working on
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clubby789.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: clubby789
github_username:  clubby789
repository: clubby789/clubby789.github.io
excerpt_separator: <!--more-->

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
site_favicon: favicon.ico

host: 0.0.0.0
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
